Add controllers
sfinkoo/shareItProject pull request #1
Opened 2023-03-26 13:04 UTC by sfinkoo

2023-04-04 14:40 UTC, afomkina requested changes

2023-04-04 14:40 UTC, afomkina commented on src/main/java/ru/practicum/shareit/AbstractDto.java
> +@Data
Лучше не использовать `@Data` бездумно, так как она несет за собой много скрытых проблем. Вот хорошая статья, вот отличная статья [про применение lombok](https://medium.com/nuances-of-programming/lombock-%D1%85%D0%BE%D1%80%D0%BE%D1%88%D0%B5%D0%B5-%D0%B8-%D0%BF%D0%BB%D0%BE%D1%85%D0%BE%D0%B5-%D0%BF%D1%80%D0%B8%D0%BC%D0%B5%D0%BD%D0%B5%D0%BD%D0%B8%D0%B5-4bd9cfdc5dd5)

2023-04-04 14:40 UTC, AnastasiyaFomkina commented on pom.xml
> +			<artifactId>spring-boot-starter-jdbc</artifactId>
В данном проекте jdbc - зависимость нам не понадобится, лучше удалить

2023-04-04 14:40 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/exception/ErrorHandler.java
> +        log.debug("Непредвиденная ошибка.");
Лучше добавить в лог вывод мессаджа сообщения:
```suggestion
        log.debug("Непредвиденная ошибка: {}", throwable.getMessage());
```

2023-04-04 14:40 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/exception/ErrorResponse.java
> +    public ErrorResponse(String error) {
`@AllArgsConstructor`

2023-04-04 14:40 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +    public ItemDto add(@Valid @RequestBody Item item, HttpServletRequest request) {
В body мы должны получать Dto объект и уже работать с ним. 
HttpServletRequest - лишний нужно от него избавиться по всему проекту

2023-04-04 14:40 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +        return Integer.parseInt(request.getHeader("X-Sharer-User-Id"));
`"X-Sharer-User-Id"` - много где еще пригодится, нужно вынести в отдельный класс и сделать публичной константой

2023-04-04 14:40 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/item/dto/ItemDto.java
>   * TODO Sprint add-controllers.
В коммерческой разработке, когда код из `TODO` реализован, принято его удалять, чтобы он не путал других разработчиков.
Удали, пожалуйста, все `TODO`, которые были выполнены во всем проекте

2023-04-04 14:40 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/item/mapping/ItemMapper.java
> +    public ItemMapper(ModelMapper mapper) {
`@RequiredArgsConstructor`

2023-04-04 14:40 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/item/mapping/ItemMapper.java
> +    public Item toEntity(ItemDto dto) {
_Саморазвитие_
Часто для маппинга сущностей также используется библиотека [Mapstruct](https://blog.skillfactory.ru/glossary/mapstruct/), которая позволяет автоматически настраивать маппинг из одной сущности в другую с помощью описания интерфейсов и аннотаций. Она автоматически генерит шаблонные методы, что позволяет только определить название метода в интерфейсе, когда нет сильных различий в сущностях. 
Вот [здесь](https://www.baeldung.com/mapstruct) есть отличный гайд для старта работы с библиотекой.
При наличии свободного времени можно поизучать

2023-04-04 14:40 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        if (item.getAvailable() != null) {
_Саморазвитие_
Кстати, `update`, можно тоже красиво сгенерировать с помощью `mapstruct`:

Можно тоже сделать с помощью мапстракт:

В первую очередь нам нужно объявить сам метод
```
Item update(Item recipient, @MappingTarget Item donor);
```
Аннотация @MappingTarget показывает в какую сущность будут маппится изменения. 
По хорошему, можно вообще сделать метод `void`, так как сущность с @MappingTarget и так уже будет содержать все изменения:
```
void update(Item recipient, @MappingTarget Item donor);
```
Соответственно, нужно научить метод обрабатывать null, для этого в настройках маппера, нужно будет добавить параметр `nullValuePropertyMappingStrategy = NullValuePropertyMappingStrategy.IGNORE`
Тогда получатся следующие настройки маппера:
```
@Mapper(
    componentModel = "spring",
    nullValuePropertyMappingStrategy = NullValuePropertyMappingStrategy.IGNORE
)
```
После всех доработок, нужно будет перегенерить проект и можно будет пользоваться сгенерированным методом

2023-04-04 14:40 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        for (ItemDto item : allItems) {
Нужно переписать с помощью цикла

2023-04-04 14:40 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/item/storage/InMemoryItemStorage.java
> +    private final HashMap<Integer, Item> items = new HashMap<>();
Принято объявлять объект с интерфейсом, а создавать с определенной реализацией. Данный подход делает программу более поддерживаемой и не зависящей от определенной реализации
```suggestion
    private final Map<Integer, Item> items = new HashMap<>();
```

2023-04-04 14:40 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +    public UserDto addUser(@Valid @RequestBody User user) throws ValidationException {
В body должен приходить Dto объект

2023-04-04 14:40 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +    public UserDto updateUser(@RequestBody User user, @PathVariable String userId) throws ValidationException {
Здесь тоже

2023-04-04 14:40 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/user/dto/UserDto.java
> +    private HashSet<Item> items;
```suggestion
    private Set<Item> items;
```

2023-04-04 14:40 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/user/model/User.java
> +    private HashSet<Item> items;
```suggestion
    private Set<Item> items;
```

2023-04-04 14:40 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +        for (User user : users) {
Нужно переписать с помощью stream api

2023-04-04 14:40 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/user/storage/InMemoryUserStorage.java
> +    private final HashMap<Integer, User> users = new HashMap<>();
```suggestion
    private final Map<Integer, User> users = new HashMap<>();
```

2023-04-04 14:47 UTC, sfinkoo commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +    public ItemDto add(@Valid @RequestBody Item item, HttpServletRequest request) {
HttpServletRequest лишний или Item?

2023-04-04 18:00 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +    public ItemDto add(@Valid @RequestBody Item item, HttpServletRequest request) {
Лишний HttpServletRequest, его нужно удалить и передавать хэдеры в параметры с помощью @RequestHeader

А Item нужно заменить на ItemDto

2023-04-05 10:34 UTC, AnastasiyaFomkina requested changes
Осталось совсем немного

2023-04-05 10:34 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/booking/Booking.java
> +@Data
Нужно избавиться от `@Data` в соответствие с данной статьей [про применение lombok](https://medium.com/nuances-of-programming/lombock-%D1%85%D0%BE%D1%80%D0%BE%D1%88%D0%B5%D0%B5-%D0%B8-%D0%BF%D0%BB%D0%BE%D1%85%D0%BE%D0%B5-%D0%BF%D1%80%D0%B8%D0%BC%D0%B5%D0%BD%D0%B5%D0%BD%D0%B8%D0%B5-4bd9cfdc5dd5)

2023-04-05 10:34 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +    public ItemDto add(@Valid @RequestBody ItemDto item, HttpServletRequest request) {
HttpServletRequest - лишний, чтобы получать хэдер нужно использовать [@RequestHeader](https://www.baeldung.com/spring-rest-http-headers). Поправь, пожалуйста, во всех контроллерах

2023-04-05 10:34 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +        return Integer.parseInt(request.getHeader("X-Sharer-User-Id"));
Нужно вынести название хэдера в публичную константу

2023-04-05 10:34 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/item/dto/ItemDto.java
>   * TODO Sprint add-controllers.
Нужно удалить все реализованные TODO

2023-04-05 10:36 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/item/mapping/ItemMapper.java
> +    public Item toEntity(ItemDto dto) {
Метод не используется, нужно использовать

2023-04-05 10:37 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/user/mapping/UserMapper.java
> +    public User toEntity(UserDto dto) {
Метод нужно использовать

2023-04-05 10:39 UTC, AnastasiyaFomkina requested changes

2023-04-05 10:39 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/item/storage/InMemoryItemStorage.java
> +    private final HashMap<Integer, ItemDto> items = new HashMap<>();
В мапу нужно класть Item, а не ItemDto. Dto нужны для обмена данными с другими системами, а обычные сущности(Item), чтобы запоминать их в память:
`Map<Integer, Item> items = new HashMap<>();`

2023-04-05 10:39 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/user/storage/InMemoryUserStorage.java
> +    private final Map<Integer, UserDto> users = new HashMap<>();
Соответственно тут тоже
```suggestion
    private final Map<Integer, User> users = new HashMap<>();
```

2023-04-06 06:47 UTC, AnastasiyaFomkina approved these changes

2023-04-06 10:46 UTC, merged